export const MODAL_OPEN = "MODAL_OPEN";

export const CONTACT_SELECTED = "CONTACT_SELECTED";

export const CONTACT_FETCH_REQUESTED = "CONTACT_FETCH_REQUESTED";
export const CONTACT_FETCH_SUCCEEDED = "CONTACT_FETCH_SUCCEEDED";
export const CONTACT_FETCH_FAILED = "CONTACT_FETCH_FAILED";

export const CONTACT_ADD_REQUESTED = "CONTACT_ADD_REQUESTED";
export const CONTACT_ADD_SUCCEEDED = "CONTACT_ADD_SUCCEEDED";
export const CONTACT_ADD_FAILED = "CONTACT_ADD_FAILED";

export const CONTACT_UPDATE_REQUESTED = "CONTACT_UPDATE_REQUESTED";
export const CONTACT_UPDATE_SUCCEEDED = "CONTACT_UPDATE_SUCCEEDED";
export const CONTACT_UPDATE_FAILED = "CONTACT_UPDATE_FAILED";

export const CONTACT_DELETE_REQUESTED = "CONTACT_DELETE_REQUESTED";
export const CONTACT_DELETE_SUCCEEDED = "CONTACT_DELETE_SUCCEEDED";
export const CONTACT_DELETE_FAILED = "CONTACT_DELETE_FAILED";
